// packages/reactui/src/app/Home.jsx
import React from 'react'
import Button from './components/Button.jsx'
import { getTenant } from './http-common.js';

// have local functions to manage on change events of the form - these don't need to be in the state
// just need the fields to be up to date when form submitted so fields can be passed on to the App and verified
// component is in two parts: static intro text and the login form
let formData = {
  username: "",
  password: ""
};
function nameChange(e) {
  formData.username = e.target.value;
}
function passwordChange(e) {
  formData.password = e.target.value;
}

const Home = (props) => (
  <div className="row well">
    <div className="col-md-6">
      <h1>Welcome to the Library Information System {getTenant()}</h1>
      <p>This sample application lets you view, create and edit books in a library catalog as well as view, create and edit authors.</p>
      <p>To view the library catalog or the authors list you will need to login as a borrower and to make changes to the list of books or authors you will need to login as a librarian.</p>
      <p>Note: This is not a real application, but is just a sample application used in the popular <a href="http://www.inflectra.com/SpiraTest">SpiraTest</a> test management system and <a href="http://www.inflectra.com/Rapise">Rapise</a> test automation system. Both of these products are created by <a href="http://www.inflectra.com/">Inflectra Corporation</a>.</p>
    </div>
    
    {!props.permission ? 
      <div className="col-md-4 col-md-offset-2">
      
        <h2>Please login</h2>
        <form>
          {props.authMessage ? 
            <div className="alert alert-warning" role="alert">{props.authMessage}</div>
            : null
          }
          <div className="form-group">
            <label htmlFor="username">Username</label>
            <input 
              type="text" 
              className="form-control" 
              id="username" 
              placeholder="Username" 
              onChange={nameChange}
              onKeyPress={ (e) => e.key === 'Enter' ? props.authHandler(formData) : null }
              />
          </div>
          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input 
              type="password" 
              className="form-control" 
              id="password" 
              placeholder="Password" 
              onChange={passwordChange}
              onKeyPress={ (e) => e.key === 'Enter' ? props.authHandler(formData) : null }
              />
          </div>
          <div>
            <Button 
              classes="btn btn-primary" 
              text="Login"
              onClick={props.authHandler}
              value={formData}
              />
          </div>
        </form>
      </div>

    :

      null

    }
  </div>

)

export default Home

// packages/angularui/src/app/features/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../../data.service';
import { LoginService, LibraryService } from 'src/app/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styles: [
  ]
})
export class HomeComponent implements OnInit {

  constructor(public loginService: LoginService, public libraryService: LibraryService, private dataService: DataService) { 

    this.dataService.userLoggedOutEvent.subscribe(() => {
      this.username = "";
      this.password = "";
    });
  }

  errorMessage: string = "";

  username: string = "";
  password: string = "";

  ngOnInit(): void 
  {
  
  }

  onLogin(valid)
  {
    if (valid)
    {
      console.log("Username: " + this.username);
      console.log("Password: " + this.password);

      this.loginService.login(this.username, this.password).then((result) =>
      {
        console.log("Logged in successfully");
        this.libraryService.loadData().then((result) => {
          console.log("Library data loaded");
        });
      },
      (error) => {
        this.errorMessage = error;
        setTimeout(() => { this.errorMessage = ""; }, 5000);      
      });
    }
  }
}

<div class="jumbotron" style="background-color: #fff; height: calc(95vh);">
<br/><br/>
<div class="row well" *ngIf="!loginService.isAuthenticated()">
    <div class="col-md-6">
      <h2>Welcome to the Library Information System</h2>
      <p>This sample application lets you view, create and edit books in a library catalog as well as view, create and edit authors.</p>
      <p>To view the library catalog or the authors list you will need to login as a borrower and to make changes to the list of books or authors you will need to login as a librarian.</p>
      <p>Note: This is not a real application, but is just a sample application used in the popular <a href="http://www.inflectra.com/SpiraTest">SpiraTest</a> test management system and <a href="http://www.inflectra.com/Rapise">Rapise</a> test automation system. Both of these products are created by <a href="http://www.inflectra.com/">Inflectra Corporation</a>.</p>
      <br/>
    </div> 
    <div class="col-md-2">
    </div>
    <div class="col-md-4">
        <h3>Please login</h3>
        <form #f="ngForm" (submit)="onLogin(f.valid)" novalidate autocomplete="off">
        <div class="form-group">
            <label for="username"><b>Username</b></label>
            <input 
            type="text" 
            class="form-control" 
            id="username" 
            name="username"
            placeholder="Username" 
            [(ngModel)]="username"
            />
        </div>
        <div class="form-group">
            <label for="password"><b>Password</b></label>
            <input 
            type="password" 
            class="form-control" 
            id="password" 
            name="password"
            placeholder="Password" 
            [(ngModel)]="password"
            />
        </div>
        <div>
            <button class="btn btn-outline-secondary" type="submit">Login</button>
        </div>
        </form>
        <br/>
        <div *ngIf="errorMessage" class="alert alert-danger">
            <span [innerText]="errorMessage"></span>
        </div>
    </div> 
</div>
<div class="row well" *ngIf="loginService.isAuthenticated()">
    <div class="col-md-6">
        <h3>{{loginService.getTenant() ? loginService.getTenant() + "'s " : ""}}System Contains</h3>
        <p><a routerLink="/authors">{{libraryService.getAuthorCount()}}</a> authors</p>        
        <p><a routerLink="/books">{{libraryService.getBookCount()}}</a> books</p>
        <p>{{libraryService.getGenreCount()}} genres</p>
        <p>Your permissions: <b>{{loginService.isAdmin() ? "Admin" : loginService.isEditor() ? "Editor" : "Reader"}}</b></p>
    </div>
</div>
</div>
